# Generated by Django 4.0.4 on 2022-04-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_person_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person_name',
        ),
    ]
