# Generated by Django 4.0.4 on 2022-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_options_remove_profile_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='study',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
