# Generated by Django 4.0.4 on 2022-05-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study',
        ),
        migrations.AddField(
            model_name='profile',
            name='group_of_study',
            field=models.CharField(db_index=True, help_text='Группа', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(db_index=True, help_text='Место обучения', max_length=200, null=True),
        ),
    ]
