# Generated by Django 4.0.4 on 2022-05-04 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_author_post_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_for_post', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
