# Generated by Django 4.0.4 on 2022-04-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_comment'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(db_index=True, max_length=200)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_for_user', to='profiles.person')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_parent', to='blog.post')),
            ],
        ),
    ]
