# Generated by Django 4.0.4 on 2022-05-06 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_comments', '0004_alter_comment_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
