# Generated by Django 4.0.4 on 2022-04-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(db_index=True, max_length=100)),
                ('post_summary', models.CharField(db_index=True, max_length=10000)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('post_likes', models.IntegerField()),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_for_user', to='profiles.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(db_index=True, max_length=200)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_for_user', to='profiles.person')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_parent', to='blog.post')),
            ],
        ),
    ]
