# Generated by Django 4.0.4 on 2022-05-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_likes',
            new_name='liked',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_summary',
            new_name='text',
        ),
    ]
