# Generated by Django 4.0.4 on 2022-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.IntegerField(null=True),
        ),
    ]
